### ISSUE TITLE
TorchIO citation

### ISSUE THREAD

**Issue by fepegar** [chfc-cmi/misas#5]
Hi there! Thanks for using and citing [TorchIO](https://arxiv.org/abs/2003.04696) in [Sensitivity analysis for interpretation of machine learning based segmentation models in cardiac MRI](https://bmcmedimaging.biomedcentral.com/articles/10.1186/s12880-021-00551-1). Please next time make sure the arXiv ID is correctly referenced (there's a dot missing) so online tools can detect the citation automatically.

**Comment by iimog** [comment]
Hi Fernando! I'm so sorry about that. I have no idea where that dot went missing. The ID is correct in my reference manager and got correctly inserted in our other publication citing `torchio`: https://link.springer.com/chapter/10.1007/978-3-030-65651-5_6
I'll write to BMC Medical Imaging to ask if that dot can be inserted and hopefully online tools are able to pick this up automatically, then. Thanks again for the great tool and sorry for the mistake. I'll keep this open until I hear back from the journal.

**Comment by fepegar** [comment]
No worries, thank you very much!

**Comment by iimog** [comment]
After many emails they finally updated the article to fix the citation: https://link.springer.com/article/10.1186/s12880-021-00551-1#change-history
The arXiv id is now correct and the link works. I do hope this makes tools automatically detect our citation of `torchio`.

**Comment by fepegar** [comment]
That's awesome, thank you very much! I'm also trying to change something on one of my articles, but Springer is ignoring all my emails :(
